config/routes.rb
Rails.application.routes.draw do
  resources :lols
  resources :users
  resources :articles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
						length: { minimum: 5 }
end

app/models/lol.rb
class Lol < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save :encrypt_password

  def encrypt_password
    if password.present?
      self.password = Digest::MD5.hexdigest(password)
    end
  end
  
	validates :login, presence: true
	validates :password, presence: true,
						length: { minimum: 6, maximum: 15}
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
		render layout: "user_header"
	end

	def show
		@article = Article.find(params[:id])

		render layout: "user_header"
	end

	def new
		@article = Article.new
		render layout: "user_header"
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new', layout: "user_header"
		end
	end

	def edit
		@article = Article.find(params[:id])

		render layout: "user_header"
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit', layout: "user_header"
		end
	end

	def destroy
		@article = Article.find(params[:id])

		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/lols_controller.rb
class LolsController < ApplicationController
  before_action :set_lol, only: [:show, :edit, :update, :destroy]

  # GET /lols
  # GET /lols.json
  def index
    @lols = Lol.all
  end

  # GET /lols/1
  # GET /lols/1.json
  def show
  end

  # GET /lols/new
  def new
    @lol = Lol.new
  end

  # GET /lols/1/edit
  def edit
  end

  # POST /lols
  # POST /lols.json
  def create
    @lol = Lol.new(lol_params)

    respond_to do |format|
      if @lol.save
        format.html { redirect_to @lol, notice: 'Lol was successfully created.' }
        format.json { render :show, status: :created, location: @lol }
      else
        format.html { render :new }
        format.json { render json: @lol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lols/1
  # PATCH/PUT /lols/1.json
  def update
    respond_to do |format|
      if @lol.update(lol_params)
        format.html { redirect_to @lol, notice: 'Lol was successfully updated.' }
        format.json { render :show, status: :ok, location: @lol }
      else
        format.html { render :edit }
        format.json { render json: @lol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lols/1
  # DELETE /lols/1.json
  def destroy
    @lol.destroy
    respond_to do |format|
      format.html { redirect_to lols_url, notice: 'Lol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lol
      @lol = Lol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lol_params
      params.require(:lol).permit(:password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    render layout: "user_header"
  end

  # GET /users/1
  # GET /users/1.json
  def show

    render layout: "user_header"
  end

  # GET /users/new
  def new
    @user = User.new

    render layout: "user_header"
  end

  # GET /users/1/edit
  def edit

    render layout: "user_header"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, layout: "user_header" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, layout: "user_header" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/lols_helper.rb
module LolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
		<% if @article.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved :
				</h2>
				<ul>
					<%= @article.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %><br/>
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :text %><br/>
			<%= f.text_area :text %>
		</p>
		<p>
			<%= f.submit "Save", :class => "btn waves-effect waves-light" %>
		</p>
	<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

	<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of articles</h1>

<div class="section">
<div class="row">	
	<div class="col s12">
		<table class="striped bordered">
			<tr>
				<th>Title</th>
				<th>Text</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
			<% @articles.each do |article| %>    
		    	<tr>
			    	<td><%= article.title %></td>
			        <td><%= article.text.truncate(100) %></td> 
					<td><%= link_to "Show", article_path(article), :class => "btn waves-effect waves-light" %></td>
					<td><%= link_to "Edit", edit_article_path(article), :class => "btn waves-effect waves-light orange" %></td>
					<td><%= link_to "Delete", article_path(article), :class => "btn waves-effect waves-light red",
						method: :delete,
						data: { confirm: 'Are you sure ?'} %></td>
				</tr>
			<% end %>
		</table>
	</div>	
</div>    
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

	<%= render 'form' %>

app/views/articles/show.html.erb
<p>
	<strong>Title :</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text :</strong>
	<%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Train</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Add article", new_article_path %></li>
        <li><%= link_to "Return to list", articles_path %></li>
        <li><%= link_to "Add user", new_user_path %></li>
        <li><%= link_to "List user", users_path %></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/lols/_form.html.erb
<%= form_for(lol) do |f| %>
  <% if lol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lol.errors.count, "error") %> prohibited this lol from being saved:</h2>

      <ul>
      <% lol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lols/edit.html.erb
<h1>Editing Lol</h1>

<%= render 'form', lol: @lol %>

<%= link_to 'Show', @lol %> |
<%= link_to 'Back', lols_path %>

app/views/lols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lols</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lols.each do |lol| %>
      <tr>
        <td><%= lol.password %></td>
        <td><%= link_to 'Show', lol %></td>
        <td><%= link_to 'Edit', edit_lol_path(lol) %></td>
        <td><%= link_to 'Destroy', lol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lol', new_lol_path %>

app/views/lols/new.html.erb
<h1>New Lol</h1>

<%= render 'form', lol: @lol %>

<%= link_to 'Back', lols_path %>

app/views/lols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @lol.password %>
</p>

<%= link_to 'Edit', edit_lol_path(@lol) %> |
<%= link_to 'Back', lols_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="bordered striped">
  <thead>
    <tr>
      <th>Login</th>
      <th>Password</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, :class => "btn waves-effect waves-light" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), :class => "btn waves-effect waves-light orange" %></td>
        <td><%= link_to 'Destroy', user, :class => "btn waves-effect waves-light red", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>